// src/lib/components/Prizes.svelte
<script lang="ts">
    import caveDown from "$lib/images/cave-down.webp";
    import caveUp from "$lib/images/cave-up.webp";
    import chestFirst from "$lib/images/chest-1st.webp";
    import chestSecond from "$lib/images/chest-2nd.webp";
    import chestThird from "$lib/images/chest-3rd.webp";
    import chest from "$lib/images/chest.webp";

    let prizes = [
        {
            label: "3",
            sup: "rd",
            open: chestThird,
            image: chest,
            card: [
                "#3 Bronze",
                "BEARER OF CLOAK OF INVISIBILITY",
                "Prizes Worth Rs.50k+ Cash Prize Worth Rs. 10000 Tons of swags and giveaways",
            ],
        },
        {
            label: "1",
            sup: "st",
            open: chestFirst,
            image: chest,
            card: [
                "#1 Gold",
                "POSESSER OF ELDER WAND",
                "Prizes Worth Rs.100k+ Cash Prize Worth Rs. 30000 +Tons of swags and giveaways",
            ],
        },
        {
            label: "2",
            sup: "nd",
            open: chestSecond,
            image: chest,
            card: [
                "#2 Silver",
                "OWNER OF RESURRECTION STONE",
                "Prizes Worth Rs.80k+ Cash Prize Rs. 20000 +Tons of swags and giveaways",
            ],
        },
    ];

    function onHover(idx: number) {
        prizes[idx].image = prizes[idx].open;
    }

    function onHoverOut(idx: number) {
        prizes[idx].image = chest;
    }
</script>

<div id="prizes">
    <div
        class="text-center h-full text-black align-middle overflow-hidden bg-no-repeat bg-cover prizes__main"
    >
        <div class="relative top-0 right-0 bottom-0 left-0 w-full h-full overflow-hidden bg-fixed">
            <img
                src={caveUp}
                class="h-[18rem] w-full z-10 overflow-clip absolute bg-no-repeat bg-cover top-0"
                alt=""
            />
            <img
                src={caveDown}
                class="h-[18rem] w-full z-10 overflow-clip absolute bg-no-repeat bg-cover bottom-0"
                alt=""
            />
            <div class="w-full mt-[12rem]">
                <p class="text-white text-7xl">Prizes</p>
            </div>
            <div
                class="hidden lg:grid lg:grid-cols-3 mt-12 mb-12 w-full h-full overflow-hidden text-white text-5xl"
            >
                {#each prizes as prize, i}
                    <div class="flex flex-col items-center z-20">
                        <div
                            class={`bg-yellow-700 w-[24rem] rounded-xl ${prize.image !== chest ? "opacity-100" : "opacity-0"}`}
                        >
                            {#each prize.card as card}
                                <p class="text-2xl">{card}</p>
                            {/each}
                        </div>
                        <img
                            src={prize.image}
                            alt=""
                            on:mouseenter={() => onHover(i)}
                            on:mouseleave={() => onHoverOut(i)}
                        />
                    </div>
                {/each}
            </div>

            <div
                class="lg:hidden grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 mt-24 w-full h-full overflow-visible text-white text-5xl"
            >
                {#each prizes as prize, i}
                    <div class="flex flex-col items-center z-20">
                        <div class={`bg-yellow-700 w-[12rem] rounded-xl`}>
                            {#each prize.card as card}
                                <p class="text-xl">{card}</p>
                            {/each}
                        </div>
                        <img src={prize.open} alt="" />
                    </div>
                {/each}
            </div>
        </div>
    </div>
</div>

// components/Prizes.tsx
export default function Prizes() {
    return (
        <section
            className="pt-20 pb-10 bg-[url('/prizes.jpg')] bg-fixed bg-cover relative bg-center scroll-mt-40"
            id="prizes"
        >
            <div className="absolute inset-0 bg-gray-200 mix-blend-multiply"></div>
            <h1 className="z-10 pt-4 font-bold tracking-wider text-center text-white uppercase text-7xl font-harry-font">
                Prizes
            </h1>

            <div
                className="flex flex-col items-center justify-center gap-4 p-4 my-20 md:flex-row md:gap-0 md:p-0"
                data-aos="fade-up"
                data-aos-easing="ease-in-out"
                data-aos-duration="800"
            >
                <div className="z-10 order-2 mt-4 overflow-hidden transition-all duration-300 shadow-lg md:order-none md:mt-0 md:-mr-4 group card w-80 h-96 rounded-2xl hover:z-30 hover:scale-105">
                    <div className="relative h-40">
                        <div
                            className="absolute inset-0"
                            style={{
                                boxShadow: "inset 0 0 0 3000px rgba(215, 215, 215, 0.192)",
                                backdropFilter: "blur(2px)",
                            }}
                        ></div>
                        <div className="absolute inset-0  bg-[url('/Snitch.png')] grayscale bg-[length:60%] bg-center bg-no-repeat"></div>
                    </div>
                    {/* <Image src={Snitch} className="object-contain h-40" /> */}
                    <div className="px-8 text-gray-800 content bg-[#ffebb3] group-hover:bg-[#ffd86b]  h-full ">
                        <h1 className="pt-4 space-x-4 text-2xl font-semibold text-center capitalize">
                            <span>#2</span> Silver
                        </h1>
                        <p className="my-1 text-xs text-center text-gray-600 uppercase">
                            Owner of Resurrection Stone
                        </p>
                        <div className="font-serif text-center">
                            <p>Prizes Worth Rs.80k+</p>
                            <br></br>
                            <p>
                                Cash Prize <b>Rs. 20000</b>
                            </p>
                            <p>+Tons of swags and giveaways</p>
                        </div>
                    </div>
                </div>
                <div className="z-20 order-1 overflow-hidden transition-all duration-300 shadow-lg md:order-none md:-mt-16 group card w-80 h-96 rounded-2xl hover:scale-105">
                    <div className="relative h-40">
                        <div
                            className="absolute inset-0"
                            style={{
                                boxShadow: "inset 0 0 0 3000px rgba(215, 215, 215, 0.192)",
                                backdropFilter: "blur(2px)",
                            }}
                        ></div>
                        <div className="absolute inset-0  bg-[url('/Snitch.png')]  bg-[length:60%] bg-center bg-no-repeat"></div>
                    </div>
                    {/* <Image src={Snitch} className="object-contain h-40" /> */}
                    <div className="px-8 text-gray-800 content bg-[#ffebb3] group-hover:bg-[#ffd86b] h-full">
                        <h1 className="pt-4 text-2xl font-semibold text-center capitalize">
                            <span>#1</span> Gold
                        </h1>
                        <p className="my-1 text-xs text-center text-gray-600 uppercase">
                            Posesser of Elder Wand
                        </p>
                        <div className="font-serif text-center">
                            <p>Prizes Worth Rs.100k+</p>
                            <br></br>
                            <p>
                                Cash Prize Worth <b>Rs. 30000</b>
                            </p>
                            <p>+Tons of swags and giveaways</p>
                        </div>
                    </div>
                </div>
                <div className="z-10 order-3 overflow-hidden transition-all duration-300 shadow-lg md:order-none md:-ml-4 group card w-80 h-96 hover:z-30 rounded-2xl hover:scale-105">
                    <div className="relative h-40">
                        <div
                            className="absolute inset-0"
                            style={{
                                boxShadow: "inset 0 0 0 3000px rgba(215, 215, 215, 0.192)",
                                backdropFilter: "blur(2px)",
                            }}
                        ></div>
                        <div className="absolute inset-0  bg-[url('/Snitch.png')] sepia  bg-[length:60%] bg-center bg-no-repeat"></div>
                    </div>
                    {/* <Image src={Snitch} className="object-contain h-40" /> */}
                    <div className=" bg-[#ffebb3] transition-all duration-300 group-hover:bg-[#ffd86b]  h-full">
                        <div className="px-8 text-gray-800">
                            <h1 className="pt-4 text-2xl font-semibold text-center capitalize">
                                <span>#3</span> Bronze
                            </h1>
                            <p className="my-1 text-xs text-center text-gray-600 uppercase">
                                Bearer of Cloak of Invisibility
                            </p>
                            <div className="font-serif text-center">
                                <p>Prizes Worth Rs.50k+</p>
                                <br></br>
                                <p>
                                    Cash Prize Worth <b>Rs. 10000</b>
                                </p>
                                <p>Tons of swags and giveaways</p>
                            </div>
                            <p>
                                {/* The cup represents the vessel of your subconscious mind; the
                five streams are your five senses and the abundant emotion and
                intuition flowing from within you. */}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    );
}
